"""Initial Migration

Revision ID: 59153af34abb
Revises: 743e33726f72
Create Date: 2019-10-31 19:20:18.159698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59153af34abb'
down_revision = '743e33726f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
